# Generated by Django 3.0.3 on 2020-02-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cooldown', models.IntegerField(default=100)),
                ('encumbrance', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=0)),
                ('bodywear', models.IntegerField(default=0)),
                ('footwear', models.IntegerField(default=0)),
                ('errors', models.CharField(max_length=255)),
                ('messages', models.CharField(max_length=500)),
            ],
        ),
    ]
