# Generated by Django 3.0.3 on 2020-02-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.IntegerField(default=0, editable=False)),
                ('difficulty', models.IntegerField(default=0)),
                ('cooldown', models.IntegerField(default=100, editable=False)),
                ('errors', models.CharField(max_length=255)),
                ('messages', models.CharField(max_length=500)),
            ],
        ),
    ]
