# Generated by Django 3.0.3 on 2020-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bodywear',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cooldown',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='encumbrance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='errors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='footwear',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='gold',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='messages',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='speed',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='strength',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='proof',
            name='cooldown',
            field=models.IntegerField(blank=True, default=100, editable=False),
        ),
        migrations.AlterField(
            model_name='proof',
            name='difficulty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proof',
            name='errors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proof',
            name='messages',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='cooldown',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='errors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='items',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
